name: CI

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v6

      - name: Create artifacts
        uses: actions/upload-artifact@master
        with:
          name: vendor
          path: vendor
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Code style
        uses: zalexki/php-cs-fixer-action@master
        with:
          other-cmds: '--stop-on-violation --dry-run'

      - name: Static analysis
        uses: php-actions/phpstan@v3
        with:
          configuration: phpstan.neon

  security:
    name: Security Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check security
        uses: docker://pplotka/local-php-security-checker-github-actions
