name: CI

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v6

      - name: Artifacts - vendor
        uses: actions/upload-artifact@master
        with:
          name: vendor
          path: vendor

      - name: Artifacts - lockfile
        uses: actions/upload-artifact@master
        with:
          name: lockfile
          path: composer.lock
  ci:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get artifacts
        uses: actions/download-artifact@v3
        with:
          name: vendor

      - name: Code style
        uses: php-actions/composer@v6
        with:
          command: cs-check

      - name: Static analysis
        uses: php-actions/phpstan@v3
        with:
          configuration: phpstan.neon

  security:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get composer.lock
        uses: actions/download-artifact@v3
        with:
          name: lockfile

      - name: Check security
        uses: docker://pplotka/local-php-security-checker-github-actions
